# Generated by Django 5.2.5 on 2025-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='vehicle_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('metro', 'Metro'), ('tram', 'Tram'), ('train', 'Train'), ('ferry', 'Ferry')], default='bus', max_length=20),
        ),
    ]
