# Generated by Django 5.2.5 on 2025-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0003_bus_owner_route_owner_alter_bus_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_speed',
            field=models.FloatField(default=0.0, help_text='Current speed in km/h'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_mobile',
            field=models.CharField(blank=True, help_text="Driver's contact number", max_length=15),
        ),
    ]
