# Generated by Django 5.2.5 on 2025-09-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0004_bus_current_speed_bus_driver_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, help_text="Driver's contact number", max_length=15)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=50)),
                ('name', models.CharField(help_text='Schedule name for easy identification', max_length=100)),
                ('start_time', models.TimeField(help_text='Schedule start time')),
                ('end_time', models.TimeField(help_text='Schedule end time')),
                ('days_of_week', models.JSONField(default=list, help_text='List of weekday numbers (0=Monday, 6=Sunday)')),
                ('effective_from', models.DateField(help_text='Date from which this schedule is effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this schedule is effective (optional)', null=True)),
                ('priority', models.IntegerField(default=1, help_text='Priority for resolving conflicting schedules')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tracking_app.bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tracking_app.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_schedules', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tracking_app.route')),
            ],
            options={
                'ordering': ['-priority', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField(help_text='Date of the exception')),
                ('exception_type', models.CharField(choices=[('override', 'Override - Replace regular schedule'), ('cancel', 'Cancel - No service'), ('driver_change', 'Driver Change Only'), ('route_change', 'Route Change Only'), ('maintenance', 'Maintenance - No service'), ('holiday', 'Holiday - No service')], max_length=20)),
                ('override_start_time', models.TimeField(blank=True, help_text='Override start time', null=True)),
                ('override_end_time', models.TimeField(blank=True, help_text='Override end time', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the exception')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='tracking_app.bus')),
                ('change_driver', models.ForeignKey(blank=True, help_text='New driver for change', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_exceptions', to='tracking_app.driver')),
                ('change_route', models.ForeignKey(blank=True, help_text='New route for change', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_exceptions', to='tracking_app.route')),
                ('override_driver', models.ForeignKey(blank=True, help_text='Driver for override', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking_app.driver')),
                ('override_route', models.ForeignKey(blank=True, help_text='Route for override', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking_app.route')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_schedule_exceptions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='tracking_app.schedule')),
            ],
            options={
                'ordering': ['exception_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('owner', 'driver_id'), name='unique_driver_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('owner', 'schedule_id'), name='unique_schedule_per_owner'),
        ),
    ]
