# Generated by Django 5.2.5 on 2025-10-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0005_driver_schedule_scheduleexception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='vehicle_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('auto', 'Auto'), ('truck', 'Truck'), ('train', 'Train'), ('ferry', 'Ferry')], default='bus', max_length=20),
        ),
    ]
